### PR TITLE
Cookbook cleanup and idempotency fixes

### PR DESCRIPTION
**Pull request by detjensrobert**
- Use line cookbook instead of Chef::Util::FileEdit for idempotency
- Add idempotency testing suite
- Cleanup README
- Cookstyle fixes for Chef 16

### CODE REVIEW

**Comment by detjensrobert** [comment]
RE: failing tests: you might want to use Cookstyle instead of ChefStyle; ChefStyle is only recommended for Chef internal projects.
From the [Chefstyle README](https://github.com/chef/chefstyle/blob/master/README.md):
> Chefstyle is not meant for consumption by cookbooks or for any general purpose uses. **Chef Users and Customers Should Generally Not Use This Tool and Should Use Cookstyle.** It is not intended for any audience outside of chef core ruby development.

**Comment by detjensrobert** [comment]
@karnauskas Have you had time to look at this?

**Comment by karnauskas** [comment]
Hi, I don't have much time actually. Initially I created it for myself to reduce time spent on manual work and never come back to this, but somehow this translate time spent on automating it :) Thanks for contributing changes btw!

Why there's need of a separate cookbook for replacing text line in a file? There was an issue leaving lock file with multiple lines of same package name, but idk if that can't be fixed with Chef's libraries? 

I started using github actions for testing, can't see workflow being updated.

Isn't cookstyle extending (and replacing) rubocop? Haven't used it much, but had impression that rubocop is not required anymore.

Is there style guide for readme, or tool to generate it? 

Sometimes I wonder why there's PR coming "from nowhere" with touches all all parts of the cookbook.

**Comment by ramereth** [comment]
@karnauskas since you're lacking in time, would you be interested in transferring this cookbook to [Sous Chefs](https://sous-chefs.org/) where others can help contribute who have more time?

**Comment by karnauskas** [comment]
@ramereth I was thinking about this ~20min ago. I think this makes sense, as it would benefit cookbook's users. What's the best way to talk about this? Slack?

**Pull request merged**
