### PR TITLE
Use comments in lockfile to avoid regex ambiguity

### LINKED ISSUE #27: Update action regex can match / delete unintended lines on CentOS 7
## :bug: Problem

**TLDR: If a package has dashes in its name, the current regex used by `:update` can match multiple package names and delete unintended locks on Centos 7 and below.**

We are using this cookbook to lock some Docker packages on Centos 7, namely `docker-ce` and `docker-ce-cli`. We have two versionlock resources `:update`ing the lock for each of those packages.

The update regex is `/^[0-9]+:$PKGNAME-.+-.+\./`, which when filled in for `docker-ce` becomes `^[0-9]+:docker-ce-.+-.+\.` The `-.+` directly following the package name matches the `-cli` of the `docker-ce-cli` lockfile line instead of the version. This would cause all matching lines--both `docker-ce` and `docker-ce-cli`--to be replaced with the `docker-ce` version string, and as of #25 any duplicate lines are removed. The line for `docker-ce-cli` is then re-added by its lock resource. 

The end result is valid, but as the `-cli` line is removed and readded each converge, this breaks idempotency.

On Centos 8, the epoch and `:` following the package name prevents this from happening.

We are in the process of updating our internal cookbooks to be idempotent and as such are just noticing this now. I believe this may have also been present with the old `Chef::FileEdit`-based resource as well, since that used the same regex.

## :bulb: Possible Solution

Updating the regex to look for a number at the start of the version string may fix this, but I am not sure if that would hold for all packages. Some might still have a number after a dash in their name and still trigger this issue, but this would solve this issue for most packages.

Proposed C6/7 regex:
```regex
/^\d+:$PKGNAME-\d.*-.+\./
```

I can make a pull request to make this change, but I wanted to see if there is a better way of handling this first.

### PR DESCRIPTION
**Pull request by detjensrobert**
Implements and fixes #27. 

Also included:
- Use library helper methods instead of in `action_class` (this follows Sous Chefs convention)
- Lock and install an older version of `gcc` from the CentOS vault repo to verify locks work
- Remove EOL CentOS 6 support

### CODE REVIEW

**Comment by detjensrobert** [comment]
@karnauskas friendly ping -- have you had some time to look at this? :slightly_smiling_face:

**Comment by karnauskas** [comment]
If there's no more changes, I can merge this (and release once have access to new computer)

**Comment by detjensrobert** [comment]
This is ready to go, merge whenever.

**Comment by ramereth** [comment]
@karnauskas thanks for the merge! When will you be able to release this to the supermarket?

**Pull request merged**
